name: Mosab Says Hello
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: MosabJob hello
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          
